config:
  request-expiration: 30

# Number of citizens allowed per city, this value is not recommended to be changed if there are already citizens in cities.
Citizens: 11
# Invitation expire (seconds)
expire: 15