name: Shibacraft
version: "${version}"
main: net.shibacraft.core.Shibacraft
api-version: 1.17
authors: [ SKJOLBERG, ImEcuadorian ]
description: Plugin of Shibacraft Network - Survival
website: https://shibacraft.net
softdepend: [PlaceholderAPI, LuckPerms]
